// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: msg/generic.proto

package msg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ApolloMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*ApolloMsg_Prop
	//	*ApolloMsg_Npblame
	//	*ApolloMsg_Eqblame
	//	*ApolloMsg_Ack
	//	*ApolloMsg_Tx
	//	*ApolloMsg_ReqBlk
	//	*ApolloMsg_ReqChain
	//	*ApolloMsg_RespBlk
	//	*ApolloMsg_RespChain
	Msg isApolloMsg_Msg `protobuf_oneof:"Msg"`
}

func (x *ApolloMsg) Reset() {
	*x = ApolloMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_generic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApolloMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApolloMsg) ProtoMessage() {}

func (x *ApolloMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_generic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApolloMsg.ProtoReflect.Descriptor instead.
func (*ApolloMsg) Descriptor() ([]byte, []int) {
	return file_msg_generic_proto_rawDescGZIP(), []int{0}
}

func (m *ApolloMsg) GetMsg() isApolloMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ApolloMsg) GetProp() *ProtoProp {
	if x, ok := x.GetMsg().(*ApolloMsg_Prop); ok {
		return x.Prop
	}
	return nil
}

func (x *ApolloMsg) GetNpblame() *NoProgressBlame {
	if x, ok := x.GetMsg().(*ApolloMsg_Npblame); ok {
		return x.Npblame
	}
	return nil
}

func (x *ApolloMsg) GetEqblame() *EquivocationBlame {
	if x, ok := x.GetMsg().(*ApolloMsg_Eqblame); ok {
		return x.Eqblame
	}
	return nil
}

func (x *ApolloMsg) GetAck() *CommitAck {
	if x, ok := x.GetMsg().(*ApolloMsg_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ApolloMsg) GetTx() []byte {
	if x, ok := x.GetMsg().(*ApolloMsg_Tx); ok {
		return x.Tx
	}
	return nil
}

func (x *ApolloMsg) GetReqBlk() *RequestBlock {
	if x, ok := x.GetMsg().(*ApolloMsg_ReqBlk); ok {
		return x.ReqBlk
	}
	return nil
}

func (x *ApolloMsg) GetReqChain() *RequestChain {
	if x, ok := x.GetMsg().(*ApolloMsg_ReqChain); ok {
		return x.ReqChain
	}
	return nil
}

func (x *ApolloMsg) GetRespBlk() *ResponseBlock {
	if x, ok := x.GetMsg().(*ApolloMsg_RespBlk); ok {
		return x.RespBlk
	}
	return nil
}

func (x *ApolloMsg) GetRespChain() *ResponseChain {
	if x, ok := x.GetMsg().(*ApolloMsg_RespChain); ok {
		return x.RespChain
	}
	return nil
}

type isApolloMsg_Msg interface {
	isApolloMsg_Msg()
}

type ApolloMsg_Prop struct {
	Prop *ProtoProp `protobuf:"bytes,1,opt,name=Prop,proto3,oneof"`
}

type ApolloMsg_Npblame struct {
	Npblame *NoProgressBlame `protobuf:"bytes,2,opt,name=Npblame,proto3,oneof"`
}

type ApolloMsg_Eqblame struct {
	Eqblame *EquivocationBlame `protobuf:"bytes,3,opt,name=Eqblame,proto3,oneof"`
}

type ApolloMsg_Ack struct {
	Ack *CommitAck `protobuf:"bytes,4,opt,name=Ack,proto3,oneof"`
}

type ApolloMsg_Tx struct {
	Tx []byte `protobuf:"bytes,5,opt,name=Tx,proto3,oneof"`
}

type ApolloMsg_ReqBlk struct {
	ReqBlk *RequestBlock `protobuf:"bytes,6,opt,name=ReqBlk,proto3,oneof"`
}

type ApolloMsg_ReqChain struct {
	ReqChain *RequestChain `protobuf:"bytes,7,opt,name=ReqChain,proto3,oneof"`
}

type ApolloMsg_RespBlk struct {
	RespBlk *ResponseBlock `protobuf:"bytes,8,opt,name=RespBlk,proto3,oneof"`
}

type ApolloMsg_RespChain struct {
	RespChain *ResponseChain `protobuf:"bytes,9,opt,name=RespChain,proto3,oneof"`
}

func (*ApolloMsg_Prop) isApolloMsg_Msg() {}

func (*ApolloMsg_Npblame) isApolloMsg_Msg() {}

func (*ApolloMsg_Eqblame) isApolloMsg_Msg() {}

func (*ApolloMsg_Ack) isApolloMsg_Msg() {}

func (*ApolloMsg_Tx) isApolloMsg_Msg() {}

func (*ApolloMsg_ReqBlk) isApolloMsg_Msg() {}

func (*ApolloMsg_ReqChain) isApolloMsg_Msg() {}

func (*ApolloMsg_RespBlk) isApolloMsg_Msg() {}

func (*ApolloMsg_RespChain) isApolloMsg_Msg() {}

var File_msg_generic_proto protoreflect.FileDescriptor

var file_msg_generic_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x0f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x6c,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x73, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d,
	0x73, 0x67, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x96, 0x03, 0x0a, 0x09, 0x41, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x4d, 0x73, 0x67,
	0x12, 0x24, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x48, 0x00,
	0x52, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x4e, 0x70, 0x62, 0x6c, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4e, 0x6f,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6c, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x4e, 0x70, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x45, 0x71, 0x62, 0x6c,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x45, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x61, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x45, 0x71, 0x62, 0x6c, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03,
	0x41, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x41, 0x63, 0x6b,
	0x12, 0x10, 0x0a, 0x02, 0x54, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x02,
	0x54, 0x78, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x42, 0x6c, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x06, 0x52, 0x65, 0x71, 0x42, 0x6c, 0x6b, 0x12,
	0x2f, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x52, 0x65, 0x71, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x12, 0x2e, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6c, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6c, 0x6b,
	0x12, 0x32, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x52, 0x65, 0x73, 0x70, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x69, 0x74, 0x68, 0x79,
	0x61, 0x62, 0x68, 0x61, 0x74, 0x6b, 0x61, 0x6a, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_msg_generic_proto_rawDescOnce sync.Once
	file_msg_generic_proto_rawDescData = file_msg_generic_proto_rawDesc
)

func file_msg_generic_proto_rawDescGZIP() []byte {
	file_msg_generic_proto_rawDescOnce.Do(func() {
		file_msg_generic_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_generic_proto_rawDescData)
	})
	return file_msg_generic_proto_rawDescData
}

var file_msg_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msg_generic_proto_goTypes = []interface{}{
	(*ApolloMsg)(nil),         // 0: msg.ApolloMsg
	(*ProtoProp)(nil),         // 1: msg.ProtoProp
	(*NoProgressBlame)(nil),   // 2: msg.NoProgressBlame
	(*EquivocationBlame)(nil), // 3: msg.EquivocationBlame
	(*CommitAck)(nil),         // 4: msg.CommitAck
	(*RequestBlock)(nil),      // 5: msg.RequestBlock
	(*RequestChain)(nil),      // 6: msg.RequestChain
	(*ResponseBlock)(nil),     // 7: msg.ResponseBlock
	(*ResponseChain)(nil),     // 8: msg.ResponseChain
}
var file_msg_generic_proto_depIdxs = []int32{
	1, // 0: msg.ApolloMsg.Prop:type_name -> msg.ProtoProp
	2, // 1: msg.ApolloMsg.Npblame:type_name -> msg.NoProgressBlame
	3, // 2: msg.ApolloMsg.Eqblame:type_name -> msg.EquivocationBlame
	4, // 3: msg.ApolloMsg.Ack:type_name -> msg.CommitAck
	5, // 4: msg.ApolloMsg.ReqBlk:type_name -> msg.RequestBlock
	6, // 5: msg.ApolloMsg.ReqChain:type_name -> msg.RequestChain
	7, // 6: msg.ApolloMsg.RespBlk:type_name -> msg.ResponseBlock
	8, // 7: msg.ApolloMsg.RespChain:type_name -> msg.ResponseChain
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_msg_generic_proto_init() }
func file_msg_generic_proto_init() {
	if File_msg_generic_proto != nil {
		return
	}
	file_msg_blame_proto_init()
	file_msg_proposal_proto_init()
	file_msg_clientAck_proto_init()
	file_msg_sync_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_generic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApolloMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_generic_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ApolloMsg_Prop)(nil),
		(*ApolloMsg_Npblame)(nil),
		(*ApolloMsg_Eqblame)(nil),
		(*ApolloMsg_Ack)(nil),
		(*ApolloMsg_Tx)(nil),
		(*ApolloMsg_ReqBlk)(nil),
		(*ApolloMsg_ReqChain)(nil),
		(*ApolloMsg_RespBlk)(nil),
		(*ApolloMsg_RespChain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_generic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_generic_proto_goTypes,
		DependencyIndexes: file_msg_generic_proto_depIdxs,
		MessageInfos:      file_msg_generic_proto_msgTypes,
	}.Build()
	File_msg_generic_proto = out.File
	file_msg_generic_proto_rawDesc = nil
	file_msg_generic_proto_goTypes = nil
	file_msg_generic_proto_depIdxs = nil
}
