// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: msg/sync.proto

package msg

import (
	chain "github.com/adithyabhatkajake/libapollo/chain"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Requesting the block with this hash
	Hash []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *RequestBlock) Reset() {
	*x = RequestBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBlock) ProtoMessage() {}

func (x *RequestBlock) ProtoReflect() protoreflect.Message {
	mi := &file_msg_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBlock.ProtoReflect.Descriptor instead.
func (*RequestBlock) Descriptor() ([]byte, []int) {
	return file_msg_sync_proto_rawDescGZIP(), []int{0}
}

func (x *RequestBlock) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ResponseBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Responding with a block for the request
	Block *chain.ProtoBlock `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
}

func (x *ResponseBlock) Reset() {
	*x = ResponseBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBlock) ProtoMessage() {}

func (x *ResponseBlock) ProtoReflect() protoreflect.Message {
	mi := &file_msg_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBlock.ProtoReflect.Descriptor instead.
func (*ResponseBlock) Descriptor() ([]byte, []int) {
	return file_msg_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBlock) GetBlock() *chain.ProtoBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type RequestChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromRound     uint64 `protobuf:"varint,1,opt,name=FromRound,proto3" json:"FromRound,omitempty"`
	LastKnownHash []byte `protobuf:"bytes,2,opt,name=LastKnownHash,proto3" json:"LastKnownHash,omitempty"`
}

func (x *RequestChain) Reset() {
	*x = RequestChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestChain) ProtoMessage() {}

func (x *RequestChain) ProtoReflect() protoreflect.Message {
	mi := &file_msg_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestChain.ProtoReflect.Descriptor instead.
func (*RequestChain) Descriptor() ([]byte, []int) {
	return file_msg_sync_proto_rawDescGZIP(), []int{2}
}

func (x *RequestChain) GetFromRound() uint64 {
	if x != nil {
		return x.FromRound
	}
	return 0
}

func (x *RequestChain) GetLastKnownHash() []byte {
	if x != nil {
		return x.LastKnownHash
	}
	return nil
}

type ResponseChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain []*chain.ProtoBlock `protobuf:"bytes,1,rep,name=Chain,proto3" json:"Chain,omitempty"`
}

func (x *ResponseChain) Reset() {
	*x = ResponseChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseChain) ProtoMessage() {}

func (x *ResponseChain) ProtoReflect() protoreflect.Message {
	mi := &file_msg_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseChain.ProtoReflect.Descriptor instead.
func (*ResponseChain) Descriptor() ([]byte, []int) {
	return file_msg_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseChain) GetChain() []*chain.ProtoBlock {
	if x != nil {
		return x.Chain
	}
	return nil
}

var File_msg_sync_proto protoreflect.FileDescriptor

var file_msg_sync_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x11, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x38, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a,
	0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x52, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x46, 0x72, 0x6f, 0x6d, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77,
	0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x4c, 0x61, 0x73,
	0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x38, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x69, 0x74, 0x68, 0x79, 0x61, 0x62, 0x68, 0x61, 0x74, 0x6b, 0x61,
	0x6a, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x62, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2f, 0x6d,
	0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_sync_proto_rawDescOnce sync.Once
	file_msg_sync_proto_rawDescData = file_msg_sync_proto_rawDesc
)

func file_msg_sync_proto_rawDescGZIP() []byte {
	file_msg_sync_proto_rawDescOnce.Do(func() {
		file_msg_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_sync_proto_rawDescData)
	})
	return file_msg_sync_proto_rawDescData
}

var file_msg_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_sync_proto_goTypes = []interface{}{
	(*RequestBlock)(nil),     // 0: msg.RequestBlock
	(*ResponseBlock)(nil),    // 1: msg.ResponseBlock
	(*RequestChain)(nil),     // 2: msg.RequestChain
	(*ResponseChain)(nil),    // 3: msg.ResponseChain
	(*chain.ProtoBlock)(nil), // 4: chain.ProtoBlock
}
var file_msg_sync_proto_depIdxs = []int32{
	4, // 0: msg.ResponseBlock.Block:type_name -> chain.ProtoBlock
	4, // 1: msg.ResponseChain.Chain:type_name -> chain.ProtoBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_msg_sync_proto_init() }
func file_msg_sync_proto_init() {
	if File_msg_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_sync_proto_goTypes,
		DependencyIndexes: file_msg_sync_proto_depIdxs,
		MessageInfos:      file_msg_sync_proto_msgTypes,
	}.Build()
	File_msg_sync_proto = out.File
	file_msg_sync_proto_rawDesc = nil
	file_msg_sync_proto_goTypes = nil
	file_msg_sync_proto_depIdxs = nil
}
